### ISSUE TITLE
Drupal 8.4 / Symfony 3.2

### ISSUE THREAD

**Issue by jasonlttl** [acquia/content-hub-php#32]
I'm starting a new project on Drupal 8.4 a little early and have noticed that I can't install the acquia_contenthub module because it depends on this library which depends on Symfony 2.7 components.

composer.json
```
  "symfony/serializer": "~2.7",
  "symfony/http-foundation": "~2.7"
```

Drupal 8.4, at rc1 now, due out in 2-3 weeks, upgrades to Symfony 3.x components and so there's an incompatibility and composer can't resolve all dependencies. Thoughts?

I'm not going to be officially launching this site until after 8.4 releases, and at this point hub integration isn't a remote priority... but I figured it was worth filing an issue to know what to expect and or raise a flag in case nobody knows about the pending incompatibility.

**Comment by tottey** [comment]
This is currently in progress of being resolved in https://backlog.acquia.com/browse/LAT-1003

**Comment by japerry** [comment]
This has been fixed
