### ISSUE TITLE
composer.json requiring outdated version of acquia/http-hmac-php "2.1"

### ISSUE THREAD

**Issue by dgpalmer** [acquia/content-hub-php#38]
Hi, I am trying to update my blt project to blt 9 but I am unable to do so because blt 9.x requires http-hmac-php 3.x but content hub requires 2.1. Are there any plans to update this soon?

Thanks,
Donovan

**Comment by ynx** [comment]
Donovan, long time no talk! We are actively working on adapting content-hub-php to http-hmac-php 3.x in this sprint. We are just starting so I don't want to be overly confident about the delivery date, but our aim is to deliver it at the end of the current quarter (i.e. end of March).

**Comment by dgpalmer** [comment]
Awesome, thanks Ynx! I am also actively working on our content hub integration. Really like what you guys did with the ContentHubFilter entity!

**Comment by ynx** [comment]
That's great Donovan! I am eager to see adaptation. I'll pass your kind compliments on ContentHubFilter to the rest of the Team!

And sorry to make you put up with the wait - adapting to 3.x is our first priority right now, hopefully we get to the bottom of it soon! Will keep you in the loop.

**Comment by japerry** [comment]
This is fixed now with Version 1.3 of the library!

**Comment by dgpalmer** [comment]
Hi, I updated to the latest version of the library and the Drupal 8 module and I am experiencing a fatal error across Drupal now.

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Acquia\ContentHubClient\ContentHub::__construct() must be of the type array, string given, called in /var/www/umgch/docroot/modules/contrib/acquia_contenthub/src/Client/ClientManager.php on line 126 and defined in /var/www/umgch/vendor/acquia/content-hub-php/src/ContentHub.php:34
Stack trace:

Any suggestions?

**Comment by japerry** [comment]
Ahh yes, you'll need the most updated version of content hub module, which will also be getting released today (we had to release the library first so the module would build correctly). 

I'll update this ticket as soon as its ready to go!
