### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by brantwynn** [acquia/content-hub-php#43]
This project slows down composer install significantly due to many old branches being traversed over during the install process. It seems many of them are likely out of date and could be deleted?

**Comment by brantwynn** [comment]
Is this library project discoverable via that service?  I think we were assuming only the actual drupal module would be discoverable under `drupal/`

**Comment by scor** [comment]
This library should be discovered via packagist, just like another composer dependency. https://packagist.org/packages/acquia/content-hub-php

**Comment by brantwynn** [comment]
Perfect. Removing the custom vcs resolved the issue. Thanks!

**Comment by scor** [comment]
Glad you got this resolved!

> However I would have expected most people to rely on the drupal.org composer, and not this private repo. Do you have any reasons to build with this repo?

Ignore my comment above, I got confused with another repo. For the record, content-hub-php is meant to be a public repository, and used like a regular composer dependency from packagist.org.
